### ISSUE TITLE
Add CDN & badge to readme

### ISSUE THREAD

**Issue by sroehrl** [gaudiamus-css/gaudiamus-css.github.io#9]
Incorporate the possibility for CDN usage [e.g. jsdelivr](https://www.jsdelivr.com/package/npm/gaudiamus-css) in the README.
However: Verbiage should make it clear that gaudiamus is best used locally where variables, modifications & compositions can be achieved.

**Comment by fonsdant** [comment]
sroehrl, I created a pull request. I added the badge, but I didn't understand the "verbiage" point.

**Comment by sroehrl** [comment]
Thank you. I commented on your PR with an explanation of what I mean. You can update the PR accordingly if you want.
